[tool.poetry]
name = "copilot"
version = "0.1.0"
description = ""
authors = ["Ryan Chui <ryan.w.chui@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
flask = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
